# mapping hosted staging to EU to avoid conflict
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hosted-color-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/color/aperture-staging
    codefresh.io/product: hosted-color
spec:
  destination:
    name: 'target-eu'
    namespace: staging
  source:
    path: manifests/color/aperture-staging
    repoURL: 'https://github.com/aperture-sci/DevOps'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
